### ISSUE TITLE
blocks other backends if no suggestions?

### ISSUE THREAD

**Issue by unhammer** [aaronjensen/company-flow#4]
I would like to combine flow with "fallbacks" to dabbrev-code, like
```
(set (make-local-variable 'company-backends)
         '((company-flow :with company-yasnippet :with company-dabbrev-code)))
```
so that in case there's something up with company-flow, I at least get dabbrevs. However, sometimes this leads to no suggestions at all. If I switch the priority to

```
(set (make-local-variable 'company-backends)
         '((company-dabbrev-code :with company-yasnippet :with company-flow)))
```
I always get suggestions, but then the company-flow ones (with good type info etc.) are last in the list. Does `company-flow` somehow block moving on to other backends?

**Comment by aaronjensen** [comment]
Hi @unhammer I believe the proper way to do this is actually something along these lines:

```
(set (make-local-variable 'company-backends)
     '((company-flow :with company-yasnippet company-dabbrev-code)
       (company-dabbrev-code :with company-yasnippet)))
```

That way if `company-flow` doesn't return a prefix it will fall back to the next list of backends. [This is what I do in my init.el](https://github.com/aaronjensen/spacemacs.d/blob/c409ebe2ccd5a3168a799adb77d332e31b77a080/lisp/init-javascript.el#L16-L21)

As an aside, `:with` applies to all succeeding backends, so you do not need to say `:with` twice.

I'm going to close this out, because I think it is actually a usage issue w/ company and there is nothing to fix in company-flow. If I'm missing something, please let me know. Thanks!

**Comment by unhammer** [comment]
Aha, that works, thanks!
